CREATE TABLE Users (
Username VARCHAR(255) NOT NULL PRIMARY KEY,
Password VARCHAR(255) NOT NULL,
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255) NOT NULL, 
Email VARCHAR(255) NOT NULL UNIQUE KEY 
);

-- ALTER TABLE Users ADD CONSTRAINT Pk_Users_Username PRIMARY KEY(Username); 
-- ALTER TABLE Users ADD CONSTRAINT Uk_Users_Email UNIQUE KEY(Email);

-- DROP TABLE Users

